default['lighttpd2']['prefix'] = '/opt/lighttpd2'
default['lighttpd2']['etc'] = '/opt/lighttpd2/etc'
default['lighttpd2']['conf_dir'] = '/opt/lighttpd2/etc/conf.d'
default['lighttpd2']['listen_addresses'] = ['0.0.0.0:80']
default['lighttpd2']['openssl']['enable'] = true
default['lighttpd2']['openssl']['listen_addresses'] = ['0.0.0.0:443']
default['lighttpd2']['modules'] = [:accesslog, :openssl, :lua, :proxy, :balance, :expire, :vhost]
default['lighttpd2']['applications'] = []
default['lighttpd2']['run_as'] = "www-data"
